[project]
name = "cofi-ldm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.0",
    "torch>=2.7.1",
    "transformers>=4.52.4",
]
